# Generated by Django 5.1 on 2025-07-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_of_guests',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='inventory',
            field=models.IntegerField(null=True),
        ),
    ]
